{
 "title": "Infocob Logs Dashboards",
 "time": { "from": "2026-04-27T03:31:00.000Z", "to": "2026-04-27T09:31:00.000Z" },
 "templating": {
  "list": [
   { "name": "Recherche", "label": "Recherche par extrait" },
   { "name": "search_label", "label": "Recherche par labels" }
  ]
 },
 "panels": [
  {
   "title": "Global",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{source=\"apache\"}|= \"$Recherche\""
    }
   ]
  },
  {
   "title": "Windows",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{os=\"windows\"}|= \"$Recherche\""
    }
   ]
  },
  {
   "title": "Linux logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{os=\"linux\"}|= \"$Recherche\""
    }
   ]
  },
  {
   "title": "Success logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{http_class=~\"redirect|success\"}|= \"$Recherche\""
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{http_class=~\"client_error|server_error\"}|= \"$Recherche\""
    }
   ]
  },
  {
   "title": "Comparaison Linux-Windows",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(os) (count_over_time({os=\"linux\"} [24h]))"
    },
    {
     "direction": "backward",
     "expr": "sum by(os) (count_over_time({os=\"windows\"} [24h]))"
    }
   ]
  },
  {
   "title": "http_class Serie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(http_class) (count_over_time({http_class=\"success\"} [24h]))"
    },
    {
     "direction": "backward",
     "expr": "sum by(http_class) (count_over_time({http_class=\"client_error\"} [24h]))"
    },
    {
     "direction": "backward",
     "expr": "sum by(http_class) (count_over_time({http_class=\"redirect\"} [24h]))"
    },
    {
     "direction": "backward",
     "expr": "sum by(http_class) (count_over_time({http_class=\"server-error\"} [24h]))"
    }
   ]
  }
 ]
}